import { prisma } from '../src/db/client.js';

const species = [
  {
    commonName: 'White Oak',
    scientificName: 'Quercus alba',
    family: 'Fagaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1360,
    density: 0.75,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; pre-drilling recommended for nailing.',
    commonUses: 'Furniture, flooring, cabinetry, barrels, boat building',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Black Walnut',
    scientificName: 'Juglans nigra',
    family: 'Juglandaceae',
    originRegions: 'Eastern United States',
    jankaHardness: 1010,
    density: 0.64,
    grainType: 'Straight, occasionally wavy',
    texture: 'Medium',
    poreStructure: 'Semi-ring-porous',
    heartwoodColor: 'Rich dark brown',
    sapwoodColor: 'Pale yellowish-gray',
    workabilityRating: 5,
    workabilityNotes:
      'Excellent workability with both hand and power tools; glues and finishes beautifully.',
    commonUses: 'Fine furniture, gunstocks, veneer, cabinetry',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Brazilian Rosewood',
    scientificName: 'Dalbergia nigra',
    family: 'Fabaceae',
    originRegions: 'Brazil',
    jankaHardness: 2720,
    density: 0.85,
    grainType: 'Straight to interlocked',
    texture: 'Medium to fine',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Dark brown with black streaks',
    sapwoodColor: 'Pale yellow',
    workabilityRating: 3,
    workabilityNotes:
      'Can be difficult to work due to high density and interlocked grain; blunts cutting edges.',
    commonUses: 'High-end furniture, musical instruments, veneer',
    sustainabilityStatus: 'Endangered',
    citesListed: true,
  },
  {
    commonName: 'Eastern White Pine',
    scientificName: 'Pinus strobus',
    family: 'Pinaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 380,
    density: 0.35,
    grainType: 'Straight',
    texture: 'Fine, even',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light brown to reddish-brown',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools; low blunting effect.',
    commonUses: 'Construction, millwork, furniture, carving',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Teak',
    scientificName: 'Tectona grandis',
    family: 'Lamiaceae',
    originRegions: 'South and Southeast Asia',
    jankaHardness: 1070,
    density: 0.65,
    grainType: 'Straight, occasionally interlocked',
    texture: 'Coarse, uneven',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Golden to dark brown',
    sapwoodColor: 'Pale yellowish-white',
    workabilityRating: 4,
    workabilityNotes: 'Naturally oily; can dull tools but machines and finishes well overall.',
    commonUses: 'Outdoor furniture, boat decking, flooring, veneer',
    sustainabilityStatus: 'Vulnerable',
    citesListed: false,
  },
  {
    commonName: 'Red Oak',
    scientificName: 'Quercus rubra',
    family: 'Fagaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1290,
    density: 0.7,
    grainType: 'Straight',
    texture: 'Coarse, open',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Reddish brown to pink',
    sapwoodColor: 'Nearly white to light brown',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; open grain can cause blotching with stain, a pre-finish conditioner is recommended.',
    commonUses: 'Furniture, flooring, cabinetry, interior trim, veneer',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Hard Maple',
    scientificName: 'Acer saccharum',
    family: 'Sapindaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1450,
    density: 0.71,
    grainType: 'Straight, occasionally curly or wavy',
    texture: 'Fine, even',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Creamy white',
    workabilityRating: 3,
    workabilityNotes:
      'Hard and dense; can be difficult to work with hand tools, machines well but blunts cutters faster than softer woods.',
    commonUses: 'Flooring, cutting boards, cabinetry, bowling alley lanes, musical instruments',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Soft Maple',
    scientificName: 'Acer rubrum',
    family: 'Sapindaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 950,
    density: 0.62,
    grainType: 'Straight, occasionally wavy',
    texture: 'Fine, even',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Pale creamy white',
    workabilityRating: 4,
    workabilityNotes:
      'Easier to work than hard maple; machines and sands well and takes stain evenly.',
    commonUses: 'Furniture, cabinetry, flooring, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Cherry',
    scientificName: 'Prunus serotina',
    family: 'Rosaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 950,
    density: 0.58,
    grainType: 'Straight',
    texture: 'Fine, satiny',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Reddish brown, darkens with age and light exposure',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 5,
    workabilityNotes:
      'Excellent workability; machines, glues, and finishes beautifully with minimal tearout.',
    commonUses: 'Fine furniture, cabinetry, veneer, musical instruments',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'English Walnut',
    scientificName: 'Juglans regia',
    family: 'Juglandaceae',
    originRegions: 'Southeastern Europe to Central Asia, widely cultivated',
    jankaHardness: 1220,
    density: 0.65,
    grainType: 'Straight, occasionally wavy or curly',
    texture: 'Medium',
    poreStructure: 'Semi-ring-porous',
    heartwoodColor: 'Light to dark brown, sometimes with purplish streaks',
    sapwoodColor: 'Pale yellowish-white',
    workabilityRating: 4,
    workabilityNotes: 'Works well with hand and machine tools; excellent for carving and turning.',
    commonUses: 'Gunstocks, fine furniture, veneer, carving',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Ash',
    scientificName: 'Fraxinus americana',
    family: 'Oleaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1320,
    density: 0.67,
    grainType: 'Straight',
    texture: 'Coarse, uniform',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown',
    sapwoodColor: 'Nearly white to light brown',
    workabilityRating: 4,
    workabilityNotes:
      'Excellent shock resistance and bending qualities; works well with hand and machine tools.',
    commonUses: 'Tool handles, baseball bats, furniture, flooring',
    sustainabilityStatus: 'Critically endangered',
    citesListed: false,
  },
  {
    commonName: 'Hickory',
    scientificName: 'Carya ovata',
    family: 'Juglandaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1880,
    density: 0.75,
    grainType: 'Straight, occasionally wavy',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown, sometimes reddish',
    sapwoodColor: 'Nearly white, wide',
    workabilityRating: 2,
    workabilityNotes:
      'Extremely hard and dense; difficult to work with hand tools and dulls cutters quickly, but has excellent shock resistance.',
    commonUses: 'Tool handles, ladders, sporting goods, flooring, smoking wood',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Poplar',
    scientificName: 'Liriodendron tulipifera',
    family: 'Magnoliaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 540,
    density: 0.45,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Yellowish brown to olive green, sometimes with dark streaks',
    sapwoodColor: 'Pale white to yellow',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; excellent for painted finishes.',
    commonUses: 'Furniture frames, plywood, millwork, painted cabinetry',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Western Red Cedar',
    scientificName: 'Thuja plicata',
    family: 'Cupressaceae',
    originRegions: 'Pacific Northwest, North America',
    jankaHardness: 350,
    density: 0.33,
    grainType: 'Straight',
    texture: 'Medium, uneven',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Reddish brown to pinkish brown',
    sapwoodColor: 'Nearly white',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; naturally resistant to decay.',
    commonUses: 'Outdoor furniture, decking, shingles, siding, canoes',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Douglas Fir',
    scientificName: 'Pseudotsuga menziesii',
    family: 'Pinaceae',
    originRegions: 'Western North America',
    jankaHardness: 660,
    density: 0.48,
    grainType: 'Straight, occasionally wavy',
    texture: 'Medium',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Pale yellow-white, not always sharply demarcated',
    workabilityRating: 4,
    workabilityNotes: 'Works well with hand and machine tools; can be prone to splintering.',
    commonUses: 'Construction lumber, plywood, flooring, timber framing',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Mahogany',
    scientificName: 'Swietenia macrophylla',
    family: 'Meliaceae',
    originRegions: 'Central and South America',
    jankaHardness: 800,
    density: 0.55,
    grainType: 'Straight, occasionally interlocked',
    texture: 'Medium',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Reddish brown, darkens with age',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 5,
    workabilityNotes: 'Excellent workability; machines, glues, and finishes exceptionally well.',
    commonUses: 'Fine furniture, boat building, musical instruments, veneer',
    sustainabilityStatus: 'Vulnerable',
    citesListed: true,
  },
  {
    commonName: 'Birch',
    scientificName: 'Betula alleghaniensis',
    family: 'Betulaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1260,
    density: 0.62,
    grainType: 'Straight, occasionally curly',
    texture: 'Fine, even',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Creamy white',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with machine tools; can be prone to tearout with hand tools on figured grain.',
    commonUses: 'Cabinetry, plywood, flooring, furniture',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Alder',
    scientificName: 'Alnus rubra',
    family: 'Betulaceae',
    originRegions: 'Pacific Northwest, North America',
    jankaHardness: 590,
    density: 0.41,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light brown to reddish brown',
    sapwoodColor: 'Not distinct from heartwood',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; takes stain and finish evenly.',
    commonUses: 'Furniture, cabinetry, electric guitar bodies, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Butternut',
    scientificName: 'Juglans cinerea',
    family: 'Juglandaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 490,
    density: 0.38,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Semi-ring-porous',
    heartwoodColor: 'Light golden brown',
    sapwoodColor: 'Pale white to light brown',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools; excellent for carving.',
    commonUses: 'Carving, furniture, cabinetry, interior trim',
    sustainabilityStatus: 'Endangered',
    citesListed: false,
  },
  {
    commonName: 'Osage Orange',
    scientificName: 'Maclura pomifera',
    family: 'Moraceae',
    originRegions: 'South-central United States',
    jankaHardness: 2620,
    density: 0.84,
    grainType: 'Straight, occasionally interlocked',
    texture: 'Fine',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Bright golden yellow, darkens to brown with age',
    sapwoodColor: 'Pale yellow, thin',
    workabilityRating: 3,
    workabilityNotes:
      'Very hard and dense; difficult to work with hand tools and blunts cutters, but turns well.',
    commonUses: 'Bows, tool handles, fence posts, turned objects',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Purpleheart',
    scientificName: 'Peltogyne paniculata',
    family: 'Fabaceae',
    originRegions: 'Central and South America',
    jankaHardness: 1860,
    density: 0.86,
    grainType: 'Straight, occasionally wavy',
    texture: 'Medium',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Dull brown when cut, turns vivid purple with light exposure',
    sapwoodColor: 'Pale yellowish-white',
    workabilityRating: 3,
    workabilityNotes:
      'Can be difficult to work due to gumminess and hardness; blunts cutters and machines better than it hand-tools.',
    commonUses: 'Fine furniture, inlay, flooring, turned objects',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Padauk',
    scientificName: 'Pterocarpus soyauxii',
    family: 'Fabaceae',
    originRegions: 'Central and West Africa',
    jankaHardness: 1725,
    density: 0.75,
    grainType: 'Straight, occasionally interlocked',
    texture: 'Coarse, open',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Bright red-orange when cut, darkens to reddish brown',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; dust can cause irritation and finishes need UV protection to slow color change.',
    commonUses: 'Fine furniture, flooring, inlay, turned objects',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Sapele',
    scientificName: 'Entandrophragma cylindricum',
    family: 'Meliaceae',
    originRegions: 'Central and West Africa',
    jankaHardness: 1410,
    density: 0.64,
    grainType: 'Interlocked, often producing a ribbon figure',
    texture: 'Medium to fine',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Medium to dark reddish brown',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 3,
    workabilityNotes:
      'Interlocked grain can cause tearout when planing; responds well to sharp tools and careful sanding.',
    commonUses: 'Furniture, veneer, boat building, musical instruments',
    sustainabilityStatus: 'Vulnerable',
    citesListed: false,
  },
  {
    commonName: 'Wenge',
    scientificName: 'Millettia laurentii',
    family: 'Fabaceae',
    originRegions: 'Central Africa',
    jankaHardness: 1930,
    density: 0.87,
    grainType: 'Straight, occasionally interlocked',
    texture: 'Coarse, open',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Dark brown with near-black streaks',
    sapwoodColor: 'Pale yellowish-white, sharply demarcated',
    workabilityRating: 2,
    workabilityNotes:
      'Difficult to work due to hardness and open pores; blunts cutters quickly and splinters can cause skin irritation.',
    commonUses: 'Fine furniture, flooring, musical instruments, turned objects',
    sustainabilityStatus: 'Endangered',
    citesListed: false,
  },
  // The entries below restore/correct commonName values that a runaway import script
  // clobbered with raw Wikidata scientific-name fallbacks (e.g. "Pinus strobus" instead of
  // "Eastern White Pine"), and add species from a requested North American species list that
  // weren't in the database at all.
  {
    commonName: 'Eastern White Pine',
    scientificName: 'Pinus strobus',
    family: 'Pinaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 380,
    density: 0.35,
    grainType: 'Straight',
    texture: 'Fine, even',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light brown to reddish-brown',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools; low blunting effect.',
    commonUses: 'Construction, millwork, furniture, carving',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Soft Maple',
    scientificName: 'Acer rubrum',
    family: 'Sapindaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 950,
    density: 0.62,
    grainType: 'Straight, occasionally wavy',
    texture: 'Fine, even',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Pale creamy white',
    workabilityRating: 4,
    workabilityNotes:
      'Easier to work than hard maple; machines and sands well and takes stain evenly.',
    commonUses: 'Furniture, cabinetry, flooring, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Black Cherry',
    scientificName: 'Prunus serotina',
    family: 'Rosaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 950,
    density: 0.58,
    grainType: 'Straight',
    texture: 'Fine, satiny',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Reddish brown, darkens with age and light exposure',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 5,
    workabilityNotes:
      'Excellent workability; machines, glues, and finishes beautifully with minimal tearout.',
    commonUses: 'Fine furniture, cabinetry, veneer, musical instruments',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'White Ash',
    scientificName: 'Fraxinus americana',
    family: 'Oleaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1320,
    density: 0.67,
    grainType: 'Straight',
    texture: 'Coarse, uniform',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown',
    sapwoodColor: 'Nearly white to light brown',
    workabilityRating: 4,
    workabilityNotes:
      'Excellent shock resistance and bending qualities; works well with hand and machine tools.',
    commonUses: 'Tool handles, baseball bats, furniture, flooring',
    sustainabilityStatus: 'Critically endangered',
    citesListed: false,
  },
  {
    commonName: 'Green Ash',
    scientificName: 'Fraxinus pennsylvanica',
    family: 'Oleaceae',
    originRegions: 'Eastern and Central North America',
    jankaHardness: 1200,
    density: 0.65,
    grainType: 'Straight',
    texture: 'Coarse, uniform',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light brown to grayish brown',
    sapwoodColor: 'Nearly white to light brown, not always sharply demarcated',
    workabilityRating: 4,
    workabilityNotes:
      'Excellent shock resistance and bending qualities; works well with hand and machine tools.',
    commonUses: 'Tool handles, sporting goods, furniture, millwork',
    sustainabilityStatus: 'Critically endangered',
    citesListed: false,
  },
  {
    commonName: 'Shagbark Hickory',
    scientificName: 'Carya ovata',
    family: 'Juglandaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1880,
    density: 0.75,
    grainType: 'Straight, occasionally wavy',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown, sometimes reddish',
    sapwoodColor: 'Nearly white, wide',
    workabilityRating: 2,
    workabilityNotes:
      'Extremely hard and dense; difficult to work with hand tools and dulls cutters quickly, but has excellent shock resistance.',
    commonUses: 'Tool handles, ladders, sporting goods, flooring, smoking wood',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Pignut Hickory',
    scientificName: 'Carya glabra',
    family: 'Juglandaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 2100,
    density: 0.75,
    grainType: 'Straight, occasionally wavy',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown, sometimes reddish',
    sapwoodColor: 'Nearly white, wide',
    workabilityRating: 2,
    workabilityNotes:
      'Extremely hard and dense, among the hardest North American hickories; difficult to work with hand tools and dulls cutters quickly.',
    commonUses: 'Tool handles, ladders, sporting goods, smoking wood, firewood',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Yellow Birch',
    scientificName: 'Betula alleghaniensis',
    family: 'Betulaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 1260,
    density: 0.62,
    grainType: 'Straight, occasionally curly',
    texture: 'Fine, even',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Creamy white',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with machine tools; can be prone to tearout with hand tools on figured grain.',
    commonUses: 'Cabinetry, plywood, flooring, furniture',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Paper Birch',
    scientificName: 'Betula papyrifera',
    family: 'Betulaceae',
    originRegions: 'Northern North America',
    jankaHardness: 910,
    density: 0.55,
    grainType: 'Straight',
    texture: 'Fine, even',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Nearly white',
    workabilityRating: 4,
    workabilityNotes: 'Works well with hand and machine tools; good for turning and steam bending.',
    commonUses: 'Plywood, turned items, toothpicks, pulpwood, canoes',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Sassafras',
    scientificName: 'Sassafras albidum',
    family: 'Lauraceae',
    originRegions: 'Eastern North America',
    jankaHardness: 630,
    density: 0.51,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to dark brown, sometimes with orange streaks',
    sapwoodColor: 'Pale yellow, thin',
    workabilityRating: 4,
    workabilityNotes:
      'Works easily with hand and machine tools; aromatic and naturally decay resistant.',
    commonUses: 'Furniture, boat building, fence posts, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'American Elm',
    scientificName: 'Ulmus americana',
    family: 'Ulmaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 830,
    density: 0.55,
    grainType: 'Interlocked',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown, sometimes reddish',
    sapwoodColor: 'Nearly white to light brown',
    workabilityRating: 3,
    workabilityNotes:
      'Interlocked grain makes splitting difficult but is excellent for bending; can be tough on tools.',
    commonUses: 'Furniture, flooring, boxes, boat building, hockey sticks',
    sustainabilityStatus: 'Endangered',
    citesListed: false,
  },
  {
    commonName: 'Slippery Elm',
    scientificName: 'Ulmus rubra',
    family: 'Ulmaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 860,
    density: 0.57,
    grainType: 'Interlocked',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light brown to reddish brown',
    sapwoodColor: 'Grayish white',
    workabilityRating: 3,
    workabilityNotes:
      'Interlocked grain resists splitting; works reasonably well with sharp tools.',
    commonUses: 'Furniture, fence posts, boxes, veneer',
    sustainabilityStatus: 'Endangered',
    citesListed: false,
  },
  {
    commonName: 'Sycamore',
    scientificName: 'Platanus occidentalis',
    family: 'Platanaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 770,
    density: 0.59,
    grainType: 'Interlocked',
    texture: 'Fine',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Light to reddish brown',
    sapwoodColor: 'Pale yellow to white',
    workabilityRating: 3,
    workabilityNotes:
      'Interlocked grain can cause tearout; often quarter-sawn to reveal an attractive fleck figure.',
    commonUses: 'Furniture, veneer, butcher blocks, boxes',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Sweetgum',
    scientificName: 'Liquidambar styraciflua',
    family: 'Altingiaceae',
    originRegions: 'Southeastern United States',
    jankaHardness: 850,
    density: 0.54,
    grainType: 'Interlocked',
    texture: 'Fine, uniform',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Reddish brown ("Redgum")',
    sapwoodColor: 'Pale pinkish white ("Sapgum")',
    workabilityRating: 3,
    workabilityNotes:
      'Interlocked grain can cause warping and tearout; machines reasonably well when dried carefully.',
    commonUses: 'Furniture, veneer, plywood, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Tulip Poplar',
    scientificName: 'Liriodendron tulipifera',
    family: 'Magnoliaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 540,
    density: 0.45,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Yellowish brown to olive green, sometimes with dark streaks',
    sapwoodColor: 'Pale white to yellow',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; excellent for painted finishes.',
    commonUses: 'Furniture frames, plywood, millwork, painted cabinetry',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Cottonwood',
    scientificName: 'Populus deltoides',
    family: 'Salicaceae',
    originRegions: 'Eastern and Central North America',
    jankaHardness: 430,
    density: 0.4,
    grainType: 'Straight, occasionally interlocked',
    texture: 'Coarse, uneven',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Grayish white to pale brown',
    sapwoodColor: 'Nearly white, not always distinct',
    workabilityRating: 3,
    workabilityNotes: 'Soft, fuzzy grain can cause tearout; needs sharp tools and careful sanding.',
    commonUses: 'Pallets, crates, plywood, pulpwood, boxes',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Aspen',
    scientificName: 'Populus tremuloides',
    family: 'Salicaceae',
    originRegions: 'Northern North America',
    jankaHardness: 350,
    density: 0.38,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Nearly white to light brown, not always distinct from sapwood',
    sapwoodColor: 'Nearly white',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; excellent for painted finishes.',
    commonUses: 'Pulpwood, matchsticks, plywood, playground equipment, saunas',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Basswood',
    scientificName: 'Tilia americana',
    family: 'Malvaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 410,
    density: 0.37,
    grainType: 'Straight',
    texture: 'Fine, even',
    poreStructure: 'Diffuse-porous',
    heartwoodColor: 'Pale white to light brown',
    sapwoodColor: 'Not always distinct from heartwood',
    workabilityRating: 5,
    workabilityNotes: 'Excellent for hand carving and turning; very easy to work with all tools.',
    commonUses: 'Carving, musical instruments, plywood, veneer',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Hackberry',
    scientificName: 'Celtis occidentalis',
    family: 'Cannabaceae',
    originRegions: 'Eastern and Central North America',
    jankaHardness: 880,
    density: 0.58,
    grainType: 'Straight, occasionally interlocked',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Pale yellow to light brown, not always distinct',
    sapwoodColor: 'Pale yellowish white',
    workabilityRating: 4,
    workabilityNotes: 'Works well with hand and machine tools; similar working properties to ash.',
    commonUses: 'Furniture, flooring, millwork, sporting goods',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Honeylocust',
    scientificName: 'Gleditsia triacanthos',
    family: 'Fabaceae',
    originRegions: 'Central United States',
    jankaHardness: 1580,
    density: 0.72,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Reddish brown to pale amber',
    sapwoodColor: 'Pale yellow, wide',
    workabilityRating: 3,
    workabilityNotes:
      'Hard and dense; works reasonably well but blunts cutters faster than softer domestic woods.',
    commonUses: 'Fence posts, furniture, flooring, turned objects',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Black Locust',
    scientificName: 'Robinia pseudoacacia',
    family: 'Fabaceae',
    originRegions: 'Eastern United States',
    jankaHardness: 1700,
    density: 0.77,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Greenish yellow to dark brown',
    sapwoodColor: 'Pale yellow, narrow',
    workabilityRating: 3,
    workabilityNotes:
      'Very hard and dense; difficult to work with hand tools and blunts cutters, but extremely durable outdoors.',
    commonUses: 'Fence posts, decking, tool handles, flooring',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Catalpa',
    scientificName: 'Catalpa speciosa',
    family: 'Bignoniaceae',
    originRegions: 'Central United States',
    jankaHardness: 550,
    density: 0.41,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light grayish brown',
    sapwoodColor: 'Pale yellowish white, thin',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools; naturally decay resistant.',
    commonUses: 'Fence posts, furniture, interior trim, boxes',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'American Chestnut',
    scientificName: 'Castanea dentata',
    family: 'Fagaceae',
    originRegions: 'Eastern United States',
    jankaHardness: 540,
    density: 0.43,
    grainType: 'Straight',
    texture: 'Coarse, open',
    poreStructure: 'Ring-porous',
    heartwoodColor: 'Light to medium brown',
    sapwoodColor: 'Pale, narrow',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; historically prized for stability and decay resistance.',
    commonUses:
      'Historic furniture, flooring, and framing; salvaged wormy chestnut for specialty furniture',
    sustainabilityStatus: 'Critically endangered',
    citesListed: false,
  },
  {
    commonName: 'Eastern Red Cedar',
    scientificName: 'Juniperus virginiana',
    family: 'Cupressaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 900,
    density: 0.51,
    grainType: 'Straight, occasionally irregular',
    texture: 'Fine',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Reddish brown to violet-brown',
    sapwoodColor: 'Nearly white to pale yellow',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; aromatic and naturally resistant to decay and insects.',
    commonUses: 'Closet linings, chests, fence posts, pencils',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Northern White Cedar',
    scientificName: 'Thuja occidentalis',
    family: 'Cupressaceae',
    originRegions: 'Northeastern North America',
    jankaHardness: 320,
    density: 0.29,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light brown to pale yellowish brown',
    sapwoodColor: 'Nearly white, narrow',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; naturally resistant to decay.',
    commonUses: 'Shingles, siding, canoes, fence posts, chests',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Sitka Spruce',
    scientificName: 'Picea sitchensis',
    family: 'Pinaceae',
    originRegions: 'Pacific Northwest coast, North America',
    jankaHardness: 510,
    density: 0.4,
    grainType: 'Straight',
    texture: 'Medium, even',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Pale yellowish white to pinkish brown',
    sapwoodColor: 'Not always distinct',
    workabilityRating: 5,
    workabilityNotes:
      'Excellent strength-to-weight ratio; works very easily with hand and machine tools.',
    commonUses: 'Aircraft construction, musical instrument soundboards, masts, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Engelmann Spruce',
    scientificName: 'Picea engelmannii',
    family: 'Pinaceae',
    originRegions: 'Western North America',
    jankaHardness: 390,
    density: 0.35,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Nearly white to pale yellow-brown',
    sapwoodColor: 'Not always distinct',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; good stiffness for its weight.',
    commonUses: 'Construction lumber, musical instrument soundboards, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Ponderosa Pine',
    scientificName: 'Pinus ponderosa',
    family: 'Pinaceae',
    originRegions: 'Western North America',
    jankaHardness: 460,
    density: 0.42,
    grainType: 'Straight',
    texture: 'Medium, uneven',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Pale yellow-white, wide',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools; low blunting effect.',
    commonUses: 'Construction lumber, millwork, furniture, paneling',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Lodgepole Pine',
    scientificName: 'Pinus contorta',
    family: 'Pinaceae',
    originRegions: 'Western North America',
    jankaHardness: 480,
    density: 0.42,
    grainType: 'Straight',
    texture: 'Medium, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light yellow to pale brown',
    sapwoodColor: 'Nearly white, wide',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools.',
    commonUses: 'Construction lumber, log homes, poles, plywood',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Sugar Pine',
    scientificName: 'Pinus lambertiana',
    family: 'Pinaceae',
    originRegions: 'Western United States',
    jankaHardness: 380,
    density: 0.36,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light brown, sometimes with a pinkish tinge',
    sapwoodColor: 'Nearly white, wide',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; excellent for carving and patternmaking.',
    commonUses: 'Millwork, patternmaking, organ pipes, carving',
    sustainabilityStatus: 'Vulnerable',
    citesListed: false,
  },
  {
    commonName: 'Western White Pine',
    scientificName: 'Pinus monticola',
    family: 'Pinaceae',
    originRegions: 'Western North America',
    jankaHardness: 420,
    density: 0.38,
    grainType: 'Straight',
    texture: 'Fine, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light reddish brown',
    sapwoodColor: 'Nearly white, wide',
    workabilityRating: 5,
    workabilityNotes:
      'Very easy to work with hand and machine tools; excellent dimensional stability.',
    commonUses: 'Millwork, patternmaking, matches, construction',
    sustainabilityStatus: 'Vulnerable',
    citesListed: false,
  },
  {
    commonName: 'Longleaf Pine',
    scientificName: 'Pinus palustris',
    family: 'Pinaceae',
    originRegions: 'Southeastern United States',
    jankaHardness: 870,
    density: 0.59,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Orange-brown to reddish brown',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; high resin content can gum up blades.',
    commonUses: 'Flooring, heavy timber framing, construction, ship building',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Slash Pine',
    scientificName: 'Pinus elliottii',
    family: 'Pinaceae',
    originRegions: 'Southeastern United States',
    jankaHardness: 690,
    density: 0.59,
    grainType: 'Straight',
    texture: 'Coarse',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Orange-brown',
    sapwoodColor: 'Pale yellow-white',
    workabilityRating: 4,
    workabilityNotes: 'Works well with hand and machine tools; resinous, can gum up blades.',
    commonUses: 'Construction lumber, plywood, poles, pulpwood',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Loblolly Pine',
    scientificName: 'Pinus taeda',
    family: 'Pinaceae',
    originRegions: 'Southeastern United States',
    jankaHardness: 690,
    density: 0.54,
    grainType: 'Straight',
    texture: 'Medium to coarse',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light yellowish brown to orange-brown',
    sapwoodColor: 'Nearly white, wide',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; one of the most commercially important pines in the U.S.',
    commonUses: 'Construction lumber, plywood, pulpwood, poles',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Western Hemlock',
    scientificName: 'Tsuga heterophylla',
    family: 'Pinaceae',
    originRegions: 'Pacific Northwest, North America',
    jankaHardness: 540,
    density: 0.45,
    grainType: 'Straight',
    texture: 'Medium, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Pale yellowish brown to light brown',
    sapwoodColor: 'Not always distinct',
    workabilityRating: 4,
    workabilityNotes: 'Works well with hand and machine tools; can splinter if not cut cleanly.',
    commonUses: 'Construction lumber, plywood, millwork, pulpwood',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Eastern Hemlock',
    scientificName: 'Tsuga canadensis',
    family: 'Pinaceae',
    originRegions: 'Eastern North America',
    jankaHardness: 500,
    density: 0.4,
    grainType: 'Straight, occasionally spiral',
    texture: 'Coarse, uneven',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Pale brown, sometimes with a reddish tinge',
    sapwoodColor: 'Not always distinct',
    workabilityRating: 3,
    workabilityNotes:
      'Prone to splitting and splintering; hard knots can be tricky to work around.',
    commonUses: 'Construction lumber, crates, pulpwood',
    sustainabilityStatus: 'Near threatened',
    citesListed: false,
  },
  {
    commonName: 'Grand Fir',
    scientificName: 'Abies grandis',
    family: 'Pinaceae',
    originRegions: 'Pacific Northwest, North America',
    jankaHardness: 390,
    density: 0.37,
    grainType: 'Straight',
    texture: 'Medium, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Nearly white to pale brown',
    sapwoodColor: 'Not always distinct',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools.',
    commonUses: 'Construction lumber, plywood, pulpwood, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'White Fir',
    scientificName: 'Abies concolor',
    family: 'Pinaceae',
    originRegions: 'Western United States',
    jankaHardness: 410,
    density: 0.37,
    grainType: 'Straight',
    texture: 'Medium, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Nearly white to pale yellowish brown',
    sapwoodColor: 'Not always distinct',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools.',
    commonUses: 'Construction lumber, millwork, Christmas trees, pulpwood',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Pacific Silver Fir',
    scientificName: 'Abies amabilis',
    family: 'Pinaceae',
    originRegions: 'Pacific Northwest coast, North America',
    jankaHardness: 430,
    density: 0.42,
    grainType: 'Straight',
    texture: 'Medium, uniform',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Nearly white',
    sapwoodColor: 'Not always distinct',
    workabilityRating: 5,
    workabilityNotes: 'Very easy to work with hand and machine tools.',
    commonUses: 'Construction lumber, pulpwood, millwork',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Tamarack',
    scientificName: 'Larix laricina',
    family: 'Pinaceae',
    originRegions: 'Northern North America',
    jankaHardness: 590,
    density: 0.53,
    grainType: 'Straight',
    texture: 'Medium, uneven',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Yellowish brown to russet brown',
    sapwoodColor: 'Nearly white, narrow',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; naturally durable and resistant to decay.',
    commonUses: 'Poles, posts, construction lumber, boat building',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
  {
    commonName: 'Baldcypress',
    scientificName: 'Taxodium distichum',
    family: 'Cupressaceae',
    originRegions: 'Southeastern United States',
    jankaHardness: 510,
    density: 0.42,
    grainType: 'Straight',
    texture: 'Medium, uneven',
    poreStructure: 'Non-porous (softwood)',
    heartwoodColor: 'Light yellowish brown to reddish brown ("pecky cypress" when spalted)',
    sapwoodColor: 'Nearly white, narrow',
    workabilityRating: 4,
    workabilityNotes:
      'Works well with hand and machine tools; naturally resistant to decay, popular for outdoor use.',
    commonUses: 'Outdoor furniture, decking, siding, boat building, mulch',
    sustainabilityStatus: 'Least concern',
    citesListed: false,
  },
];

async function main() {
  for (const record of species) {
    await prisma.species.upsert({
      where: { scientificName: record.scientificName },
      update: record,
      create: record,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
