/**
 * Imports authoritative wood property data from the USDA Forest Products Laboratory
 * Wood Handbook — Wood as an Engineering Material (General Technical Report FPL-GTR-282,
 * 2021, public domain). https://www.fpl.fs.usda.gov/documnts/fplgtr/fplgtr282/
 *
 * Data source and how it was obtained:
 *  - Chapter 5 ("Mechanical Properties of Wood"), Table 5-3b (inch-pound units): modulus of
 *    rupture, modulus of elasticity, compression strength parallel to grain, side hardness
 *    (Janka, modified 11.28-mm-ball test), and specific gravity — all at 12% moisture content,
 *    the standard reference condition.
 *  - Chapter 4 ("Moisture Relations and Physical Properties of Wood"), Table 4-3: radial,
 *    tangential, and volumetric shrinkage (green to ovendry).
 *  - Chapter 14 ("Biodeterioration of Wood"), Table 14-1: natural heartwood decay resistance
 *    grouping (Very resistant / Resistant / Moderately resistant / Slightly or nonresistant).
 *  - These chapters were fetched directly from fpl.fs.usda.gov and read in full; the values
 *    below are transcribed from those tables, not estimated or AI-generated.
 *
 * Explicitly NOT included: "drying difficulty" (requested in the original task) has no
 * per-species rating anywhere in FPL-GTR-282 — that granular kiln-schedule-by-species data
 * lives in a separate USDA publication (the Dry Kiln Operator's Manual, Agriculture Handbook
 * 188), which this script does not have access to. The `dryingDifficulty` column exists on
 * the schema but is deliberately left null here rather than filled with a guess.
 *
 * Scope: only species already present in the WoodID database (matched by scientificName) that
 * are also covered by Table 5-3b (the "commercially important woods grown in the United
 * States" table) were included — per the task's "only update fields where we have authoritative
 * USDA data" instruction. This is a subset of Table 5-3b's ~150 species and does not cover the
 * Canadian (5-4) or non-Canadian imported (5-5) tables, which could be a follow-up pass.
 *
 * A handful of species have a decay-resistance or Janka rating that in the source table applies
 * specifically to "old growth" material (Baldcypress, Eastern White Pine, Longleaf Pine, Slash
 * Pine, Redwood) — our DB has one generic row per species with no old/young-growth split, so the
 * old-growth rating (the one associated with heartwood durability marketing/common usage) was
 * used; this is noted per-entry below.
 */

import { prisma } from '../src/db/client.js';

const ATTRIBUTION =
  'Wood properties data from the Wood Handbook, USDA Forest Products Laboratory (public domain)';

interface USDARecord {
  scientificName: string;
  specificGravity: number;
  modulusOfRupture: number; // psi
  modulusOfElasticity: number; // psi
  compressionStrengthParallel: number; // psi
  jankaHardness: number | null; // lbf — null where Table 5-3b has no value ("—")
  shrinkageRadial: number | null;
  shrinkageTangential: number | null;
  shrinkageVolumetric: number | null;
  decayResistance: string | null;
}

const VERY_RESISTANT = 'Very resistant';
const RESISTANT = 'Resistant';
const MODERATELY_RESISTANT = 'Moderately resistant';
const NONRESISTANT = 'Slightly or nonresistant';

const RECORDS: USDARecord[] = [
  // Hardwoods
  {
    scientificName: 'Alnus rubra',
    specificGravity: 0.41,
    modulusOfRupture: 9800,
    modulusOfElasticity: 1380000,
    compressionStrengthParallel: 5820,
    jankaHardness: 590,
    shrinkageRadial: 4.4,
    shrinkageTangential: 7.3,
    shrinkageVolumetric: 12.6,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Fraxinus americana',
    specificGravity: 0.6,
    modulusOfRupture: 15400,
    modulusOfElasticity: 1740000,
    compressionStrengthParallel: 7410,
    jankaHardness: 1320,
    shrinkageRadial: 4.9,
    shrinkageTangential: 7.8,
    shrinkageVolumetric: 13.3,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Fraxinus nigra',
    specificGravity: 0.49,
    modulusOfRupture: 12600,
    modulusOfElasticity: 1600000,
    compressionStrengthParallel: 5970,
    jankaHardness: 850,
    shrinkageRadial: 5.0,
    shrinkageTangential: 7.8,
    shrinkageVolumetric: 15.2,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Fraxinus pennsylvanica',
    specificGravity: 0.56,
    modulusOfRupture: 14100,
    modulusOfElasticity: 1660000,
    compressionStrengthParallel: 7080,
    jankaHardness: 1200,
    shrinkageRadial: 4.6,
    shrinkageTangential: 7.1,
    shrinkageVolumetric: 12.5,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Fraxinus quadrangulata',
    specificGravity: 0.58,
    modulusOfRupture: 13800,
    modulusOfElasticity: 1400000,
    compressionStrengthParallel: 6980,
    jankaHardness: null,
    shrinkageRadial: 3.9,
    shrinkageTangential: 6.5,
    shrinkageVolumetric: 11.7,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Populus tremuloides',
    specificGravity: 0.38,
    modulusOfRupture: 8400,
    modulusOfElasticity: 1180000,
    compressionStrengthParallel: 4250,
    jankaHardness: 350,
    shrinkageRadial: 3.5,
    shrinkageTangential: 6.7,
    shrinkageVolumetric: 11.5,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Tilia americana',
    specificGravity: 0.37,
    modulusOfRupture: 8700,
    modulusOfElasticity: 1460000,
    compressionStrengthParallel: 4730,
    jankaHardness: 410,
    shrinkageRadial: 6.6,
    shrinkageTangential: 9.3,
    shrinkageVolumetric: 15.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Fagus grandifolia',
    specificGravity: 0.64,
    modulusOfRupture: 14900,
    modulusOfElasticity: 1720000,
    compressionStrengthParallel: 7300,
    jankaHardness: 1300,
    shrinkageRadial: 5.5,
    shrinkageTangential: 11.9,
    shrinkageVolumetric: 17.2,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Betula alleghaniensis',
    specificGravity: 0.62,
    modulusOfRupture: 16600,
    modulusOfElasticity: 2010000,
    compressionStrengthParallel: 8170,
    jankaHardness: 1260,
    shrinkageRadial: 7.3,
    shrinkageTangential: 9.5,
    shrinkageVolumetric: 16.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Betula papyrifera',
    specificGravity: 0.55,
    modulusOfRupture: 12300,
    modulusOfElasticity: 1590000,
    compressionStrengthParallel: 5690,
    jankaHardness: 910,
    shrinkageRadial: 6.3,
    shrinkageTangential: 8.6,
    shrinkageVolumetric: 16.2,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Juglans cinerea',
    specificGravity: 0.38,
    modulusOfRupture: 8100,
    modulusOfElasticity: 1180000,
    compressionStrengthParallel: 5110,
    jankaHardness: 490,
    shrinkageRadial: 3.4,
    shrinkageTangential: 6.4,
    shrinkageVolumetric: 10.6,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Prunus serotina',
    specificGravity: 0.5,
    modulusOfRupture: 12300,
    modulusOfElasticity: 1490000,
    compressionStrengthParallel: 7110,
    jankaHardness: 950,
    shrinkageRadial: 3.7,
    shrinkageTangential: 7.1,
    shrinkageVolumetric: 11.5,
    decayResistance: MODERATELY_RESISTANT,
  },
  {
    scientificName: 'Castanea dentata',
    specificGravity: 0.43,
    modulusOfRupture: 8600,
    modulusOfElasticity: 1230000,
    compressionStrengthParallel: 5320,
    jankaHardness: 540,
    shrinkageRadial: 3.4,
    shrinkageTangential: 6.7,
    shrinkageVolumetric: 11.6,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Populus deltoides',
    specificGravity: 0.4,
    modulusOfRupture: 8500,
    modulusOfElasticity: 1370000,
    compressionStrengthParallel: 4910,
    jankaHardness: 430,
    shrinkageRadial: 3.9,
    shrinkageTangential: 9.2,
    shrinkageVolumetric: 13.9,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Ulmus americana',
    specificGravity: 0.5,
    modulusOfRupture: 11800,
    modulusOfElasticity: 1340000,
    compressionStrengthParallel: 5520,
    jankaHardness: 830,
    shrinkageRadial: 4.2,
    shrinkageTangential: 9.5,
    shrinkageVolumetric: 14.6,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Ulmus rubra',
    specificGravity: 0.53,
    modulusOfRupture: 13000,
    modulusOfElasticity: 1490000,
    compressionStrengthParallel: 6360,
    jankaHardness: 860,
    shrinkageRadial: 4.9,
    shrinkageTangential: 8.9,
    shrinkageVolumetric: 13.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Ulmus thomasii',
    specificGravity: 0.63,
    modulusOfRupture: 14800,
    modulusOfElasticity: 1540000,
    compressionStrengthParallel: 7050,
    jankaHardness: 1320,
    shrinkageRadial: 4.8,
    shrinkageTangential: 8.1,
    shrinkageVolumetric: 14.9,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Celtis occidentalis',
    specificGravity: 0.53,
    modulusOfRupture: 11000,
    modulusOfElasticity: 1190000,
    compressionStrengthParallel: 5440,
    jankaHardness: 880,
    shrinkageRadial: 4.8,
    shrinkageTangential: 8.9,
    shrinkageVolumetric: 13.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Carya illinoinensis',
    specificGravity: 0.66,
    modulusOfRupture: 13700,
    modulusOfElasticity: 1730000,
    compressionStrengthParallel: 7850,
    jankaHardness: 1820,
    shrinkageRadial: 4.9,
    shrinkageTangential: 8.9,
    shrinkageVolumetric: 13.6,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Carya cordiformis',
    specificGravity: 0.66,
    modulusOfRupture: 17100,
    modulusOfElasticity: 1790000,
    compressionStrengthParallel: 9040,
    jankaHardness: null,
    shrinkageRadial: 4.9,
    shrinkageTangential: 8.9,
    shrinkageVolumetric: 13.6,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Carya glabra',
    specificGravity: 0.75,
    modulusOfRupture: 20100,
    modulusOfElasticity: 2260000,
    compressionStrengthParallel: 9190,
    jankaHardness: 2140,
    shrinkageRadial: 7.2,
    shrinkageTangential: 11.5,
    shrinkageVolumetric: 17.9,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Carya ovata',
    specificGravity: 0.72,
    modulusOfRupture: 20200,
    modulusOfElasticity: 2160000,
    compressionStrengthParallel: 9210,
    jankaHardness: 1880,
    shrinkageRadial: 7.0,
    shrinkageTangential: 10.5,
    shrinkageVolumetric: 16.7,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Gleditsia triacanthos',
    specificGravity: 0.6,
    modulusOfRupture: 14700,
    modulusOfElasticity: 1630000,
    compressionStrengthParallel: 7500,
    jankaHardness: 1580,
    shrinkageRadial: 4.2,
    shrinkageTangential: 6.6,
    shrinkageVolumetric: 10.8,
    decayResistance: MODERATELY_RESISTANT,
  },
  {
    scientificName: 'Robinia pseudoacacia',
    specificGravity: 0.69,
    modulusOfRupture: 19400,
    modulusOfElasticity: 2050000,
    compressionStrengthParallel: 10180,
    jankaHardness: 1700,
    shrinkageRadial: 4.6,
    shrinkageTangential: 7.2,
    shrinkageVolumetric: 10.2,
    decayResistance: VERY_RESISTANT,
  },
  {
    scientificName: 'Acer macrophyllum',
    specificGravity: 0.48,
    modulusOfRupture: 10700,
    modulusOfElasticity: 1450000,
    compressionStrengthParallel: 5950,
    jankaHardness: 850,
    shrinkageRadial: 3.7,
    shrinkageTangential: 7.1,
    shrinkageVolumetric: 11.6,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Acer rubrum',
    specificGravity: 0.54,
    modulusOfRupture: 13400,
    modulusOfElasticity: 1640000,
    compressionStrengthParallel: 6540,
    jankaHardness: 950,
    shrinkageRadial: 4.0,
    shrinkageTangential: 8.2,
    shrinkageVolumetric: 12.6,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Acer saccharinum',
    specificGravity: 0.47,
    modulusOfRupture: 8900,
    modulusOfElasticity: 1140000,
    compressionStrengthParallel: 5220,
    jankaHardness: 700,
    shrinkageRadial: 3.0,
    shrinkageTangential: 7.2,
    shrinkageVolumetric: 12.0,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Acer saccharum',
    specificGravity: 0.63,
    modulusOfRupture: 15800,
    modulusOfElasticity: 1830000,
    compressionStrengthParallel: 7830,
    jankaHardness: 1450,
    shrinkageRadial: 4.8,
    shrinkageTangential: 9.9,
    shrinkageVolumetric: 14.7,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Quercus rubra',
    specificGravity: 0.63,
    modulusOfRupture: 14300,
    modulusOfElasticity: 1820000,
    compressionStrengthParallel: 6760,
    jankaHardness: 1290,
    shrinkageRadial: 4.0,
    shrinkageTangential: 8.6,
    shrinkageVolumetric: 13.7,
    decayResistance: null,
  },
  {
    scientificName: 'Quercus alba',
    specificGravity: 0.68,
    modulusOfRupture: 15200,
    modulusOfElasticity: 1780000,
    compressionStrengthParallel: 7440,
    jankaHardness: 1360,
    shrinkageRadial: 5.6,
    shrinkageTangential: 10.5,
    shrinkageVolumetric: 16.3,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Sassafras albidum',
    specificGravity: 0.46,
    modulusOfRupture: 9000,
    modulusOfElasticity: 1120000,
    compressionStrengthParallel: 4760,
    jankaHardness: null,
    shrinkageRadial: 4.0,
    shrinkageTangential: 6.2,
    shrinkageVolumetric: 10.3,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Liquidambar styraciflua',
    specificGravity: 0.52,
    modulusOfRupture: 12500,
    modulusOfElasticity: 1640000,
    compressionStrengthParallel: 6320,
    jankaHardness: 850,
    shrinkageRadial: 5.3,
    shrinkageTangential: 10.2,
    shrinkageVolumetric: 15.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Platanus occidentalis',
    specificGravity: 0.49,
    modulusOfRupture: 10000,
    modulusOfElasticity: 1420000,
    compressionStrengthParallel: 5380,
    jankaHardness: 770,
    shrinkageRadial: 5.0,
    shrinkageTangential: 8.4,
    shrinkageVolumetric: 14.1,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Juglans nigra',
    specificGravity: 0.55,
    modulusOfRupture: 14600,
    modulusOfElasticity: 1680000,
    compressionStrengthParallel: 7580,
    jankaHardness: 1010,
    shrinkageRadial: 5.5,
    shrinkageTangential: 7.8,
    shrinkageVolumetric: 12.8,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Liriodendron tulipifera',
    specificGravity: 0.42,
    modulusOfRupture: 10100,
    modulusOfElasticity: 1580000,
    compressionStrengthParallel: 5540,
    jankaHardness: 540,
    shrinkageRadial: 4.6,
    shrinkageTangential: 8.2,
    shrinkageVolumetric: 12.7,
    decayResistance: NONRESISTANT,
  },

  // Softwoods
  {
    scientificName: 'Taxodium distichum',
    specificGravity: 0.46,
    modulusOfRupture: 10600,
    modulusOfElasticity: 1440000,
    compressionStrengthParallel: 6360,
    jankaHardness: 510,
    shrinkageRadial: null,
    shrinkageTangential: null,
    shrinkageVolumetric: null,
    decayResistance: RESISTANT,
  }, // old-growth rating; table splits old/young growth
  {
    scientificName: 'Juniperus virginiana',
    specificGravity: 0.47,
    modulusOfRupture: 8800,
    modulusOfElasticity: 880000,
    compressionStrengthParallel: 6020,
    jankaHardness: null,
    shrinkageRadial: 3.1,
    shrinkageTangential: 4.7,
    shrinkageVolumetric: 7.8,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Calocedrus decurrens',
    specificGravity: 0.37,
    modulusOfRupture: 8000,
    modulusOfElasticity: 1040000,
    compressionStrengthParallel: 5200,
    jankaHardness: 470,
    shrinkageRadial: 3.3,
    shrinkageTangential: 5.2,
    shrinkageVolumetric: 7.7,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Thuja occidentalis',
    specificGravity: 0.31,
    modulusOfRupture: 6500,
    modulusOfElasticity: 800000,
    compressionStrengthParallel: 3960,
    jankaHardness: 320,
    shrinkageRadial: 2.2,
    shrinkageTangential: 4.9,
    shrinkageVolumetric: 7.2,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Chamaecyparis lawsoniana',
    specificGravity: 0.43,
    modulusOfRupture: 12700,
    modulusOfElasticity: 1700000,
    compressionStrengthParallel: 6250,
    jankaHardness: 630,
    shrinkageRadial: 4.6,
    shrinkageTangential: 6.9,
    shrinkageVolumetric: 10.1,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Thuja plicata',
    specificGravity: 0.32,
    modulusOfRupture: 7500,
    modulusOfElasticity: 1110000,
    compressionStrengthParallel: 4560,
    jankaHardness: 350,
    shrinkageRadial: 2.4,
    shrinkageTangential: 5.0,
    shrinkageVolumetric: 6.8,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Cupressus nootkatensis',
    specificGravity: 0.44,
    modulusOfRupture: 11100,
    modulusOfElasticity: 1420000,
    compressionStrengthParallel: 6310,
    jankaHardness: 580,
    shrinkageRadial: 2.8,
    shrinkageTangential: 6.0,
    shrinkageVolumetric: 9.2,
    decayResistance: RESISTANT,
  },
  {
    scientificName: 'Pseudotsuga menziesii',
    specificGravity: 0.48,
    modulusOfRupture: 12400,
    modulusOfElasticity: 1950000,
    compressionStrengthParallel: 7230,
    jankaHardness: 710,
    shrinkageRadial: 4.8,
    shrinkageTangential: 7.6,
    shrinkageVolumetric: 12.4,
    decayResistance: MODERATELY_RESISTANT,
  },
  {
    scientificName: 'Abies balsamea',
    specificGravity: 0.35,
    modulusOfRupture: 9200,
    modulusOfElasticity: 1450000,
    compressionStrengthParallel: 5280,
    jankaHardness: 380,
    shrinkageRadial: 2.9,
    shrinkageTangential: 6.9,
    shrinkageVolumetric: 11.2,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Abies grandis',
    specificGravity: 0.37,
    modulusOfRupture: 8900,
    modulusOfElasticity: 1570000,
    compressionStrengthParallel: 5290,
    jankaHardness: 490,
    shrinkageRadial: 3.4,
    shrinkageTangential: 7.5,
    shrinkageVolumetric: 11.0,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Abies amabilis',
    specificGravity: 0.43,
    modulusOfRupture: 11000,
    modulusOfElasticity: 1760000,
    compressionStrengthParallel: 6410,
    jankaHardness: 430,
    shrinkageRadial: 4.4,
    shrinkageTangential: 9.2,
    shrinkageVolumetric: 13.0,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Abies lasiocarpa',
    specificGravity: 0.32,
    modulusOfRupture: 8600,
    modulusOfElasticity: 1290000,
    compressionStrengthParallel: 4860,
    jankaHardness: 350,
    shrinkageRadial: 2.6,
    shrinkageTangential: 7.4,
    shrinkageVolumetric: 9.4,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Abies concolor',
    specificGravity: 0.39,
    modulusOfRupture: 9800,
    modulusOfElasticity: 1500000,
    compressionStrengthParallel: 5800,
    jankaHardness: 480,
    shrinkageRadial: 3.3,
    shrinkageTangential: 7.0,
    shrinkageVolumetric: 9.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Tsuga canadensis',
    specificGravity: 0.4,
    modulusOfRupture: 8900,
    modulusOfElasticity: 1200000,
    compressionStrengthParallel: 5410,
    jankaHardness: 500,
    shrinkageRadial: 3.0,
    shrinkageTangential: 6.8,
    shrinkageVolumetric: 9.7,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Tsuga heterophylla',
    specificGravity: 0.45,
    modulusOfRupture: 11300,
    modulusOfElasticity: 1630000,
    compressionStrengthParallel: 7200,
    jankaHardness: 540,
    shrinkageRadial: 4.2,
    shrinkageTangential: 7.8,
    shrinkageVolumetric: 12.4,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Larix occidentalis',
    specificGravity: 0.52,
    modulusOfRupture: 13000,
    modulusOfElasticity: 1870000,
    compressionStrengthParallel: 7620,
    jankaHardness: 830,
    shrinkageRadial: 4.5,
    shrinkageTangential: 9.1,
    shrinkageVolumetric: 14.0,
    decayResistance: MODERATELY_RESISTANT,
  },
  {
    scientificName: 'Pinus strobus',
    specificGravity: 0.35,
    modulusOfRupture: 8600,
    modulusOfElasticity: 1240000,
    compressionStrengthParallel: 4800,
    jankaHardness: 380,
    shrinkageRadial: 2.1,
    shrinkageTangential: 6.1,
    shrinkageVolumetric: 8.2,
    decayResistance: MODERATELY_RESISTANT,
  }, // old-growth rating
  {
    scientificName: 'Pinus taeda',
    specificGravity: 0.51,
    modulusOfRupture: 12800,
    modulusOfElasticity: 1790000,
    compressionStrengthParallel: 7130,
    jankaHardness: 690,
    shrinkageRadial: 4.8,
    shrinkageTangential: 7.4,
    shrinkageVolumetric: 12.3,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Pinus contorta',
    specificGravity: 0.41,
    modulusOfRupture: 9400,
    modulusOfElasticity: 1340000,
    compressionStrengthParallel: 5370,
    jankaHardness: 480,
    shrinkageRadial: 4.3,
    shrinkageTangential: 6.7,
    shrinkageVolumetric: 11.1,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Pinus palustris',
    specificGravity: 0.59,
    modulusOfRupture: 14500,
    modulusOfElasticity: 1980000,
    compressionStrengthParallel: 8470,
    jankaHardness: 870,
    shrinkageRadial: 5.1,
    shrinkageTangential: 7.5,
    shrinkageVolumetric: 12.2,
    decayResistance: MODERATELY_RESISTANT,
  }, // old-growth rating
  {
    scientificName: 'Pinus ponderosa',
    specificGravity: 0.4,
    modulusOfRupture: 9400,
    modulusOfElasticity: 1290000,
    compressionStrengthParallel: 5320,
    jankaHardness: 460,
    shrinkageRadial: 3.9,
    shrinkageTangential: 6.2,
    shrinkageVolumetric: 9.7,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Pinus elliottii',
    specificGravity: 0.59,
    modulusOfRupture: 16300,
    modulusOfElasticity: 1980000,
    compressionStrengthParallel: 8140,
    jankaHardness: null,
    shrinkageRadial: 5.4,
    shrinkageTangential: 7.6,
    shrinkageVolumetric: 12.1,
    decayResistance: MODERATELY_RESISTANT,
  }, // old-growth rating
  {
    scientificName: 'Pinus lambertiana',
    specificGravity: 0.36,
    modulusOfRupture: 8200,
    modulusOfElasticity: 1190000,
    compressionStrengthParallel: 4460,
    jankaHardness: 380,
    shrinkageRadial: 2.9,
    shrinkageTangential: 5.6,
    shrinkageVolumetric: 7.9,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Pinus monticola',
    specificGravity: 0.38,
    modulusOfRupture: 9700,
    modulusOfElasticity: 1460000,
    compressionStrengthParallel: 5040,
    jankaHardness: 420,
    shrinkageRadial: 4.1,
    shrinkageTangential: 7.4,
    shrinkageVolumetric: 11.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Sequoia sempervirens',
    specificGravity: 0.4,
    modulusOfRupture: 10000,
    modulusOfElasticity: 1340000,
    compressionStrengthParallel: 6150,
    jankaHardness: 480,
    shrinkageRadial: 2.6,
    shrinkageTangential: 4.4,
    shrinkageVolumetric: 6.8,
    decayResistance: RESISTANT,
  }, // old-growth rating
  {
    scientificName: 'Picea mariana',
    specificGravity: 0.42,
    modulusOfRupture: 10800,
    modulusOfElasticity: 1610000,
    compressionStrengthParallel: 5960,
    jankaHardness: 530,
    shrinkageRadial: 4.1,
    shrinkageTangential: 6.8,
    shrinkageVolumetric: 11.3,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Picea engelmannii',
    specificGravity: 0.35,
    modulusOfRupture: 9300,
    modulusOfElasticity: 1300000,
    compressionStrengthParallel: 4480,
    jankaHardness: 390,
    shrinkageRadial: 3.8,
    shrinkageTangential: 7.1,
    shrinkageVolumetric: 11.0,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Picea rubens',
    specificGravity: 0.4,
    modulusOfRupture: 10800,
    modulusOfElasticity: 1660000,
    compressionStrengthParallel: 5540,
    jankaHardness: 530,
    shrinkageRadial: 3.8,
    shrinkageTangential: 7.8,
    shrinkageVolumetric: 11.8,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Picea sitchensis',
    specificGravity: 0.4,
    modulusOfRupture: 10200,
    modulusOfElasticity: 1570000,
    compressionStrengthParallel: 5610,
    jankaHardness: 510,
    shrinkageRadial: 4.3,
    shrinkageTangential: 7.5,
    shrinkageVolumetric: 11.5,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Picea glauca',
    specificGravity: 0.36,
    modulusOfRupture: 9400,
    modulusOfElasticity: 1430000,
    compressionStrengthParallel: 5180,
    jankaHardness: 410,
    shrinkageRadial: null,
    shrinkageTangential: null,
    shrinkageVolumetric: null,
    decayResistance: NONRESISTANT,
  },
  {
    scientificName: 'Larix laricina',
    specificGravity: 0.53,
    modulusOfRupture: 11600,
    modulusOfElasticity: 1640000,
    compressionStrengthParallel: 7160,
    jankaHardness: 590,
    shrinkageRadial: 3.7,
    shrinkageTangential: 7.4,
    shrinkageVolumetric: 13.6,
    decayResistance: MODERATELY_RESISTANT,
  },
];

async function main() {
  let updated = 0;
  let notFound = 0;

  for (const record of RECORDS) {
    const existing = await prisma.species.findUnique({
      where: { scientificName: record.scientificName },
    });
    if (!existing) {
      console.warn(`  No DB row for ${record.scientificName} — skipping.`);
      notFound += 1;
      continue;
    }

    await prisma.species.update({
      where: { scientificName: record.scientificName },
      data: {
        density: record.specificGravity,
        modulusOfRupture: record.modulusOfRupture,
        modulusOfElasticity: record.modulusOfElasticity,
        compressionStrengthParallel: record.compressionStrengthParallel,
        ...(record.jankaHardness != null ? { jankaHardness: record.jankaHardness } : {}),
        shrinkageRadial: record.shrinkageRadial,
        shrinkageTangential: record.shrinkageTangential,
        shrinkageVolumetric: record.shrinkageVolumetric,
        decayResistance: record.decayResistance,
        attribution: ATTRIBUTION,
      },
    });
    console.log(`Updated ${record.scientificName} (${existing.commonName})`);
    updated += 1;
  }

  console.log(`\nDone. Updated ${updated} species, ${notFound} not found in DB.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
